// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot18;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX rightMotor1;
    public static WPI_TalonSRX rightMotor2;
    public static WPI_TalonSRX rightMotor3E;
    public static WPI_TalonSRX leftMotor1E;
    public static WPI_TalonSRX leftMotor2;
    public static WPI_TalonSRX leftMotor3;
    public static Encoder rightEnc;
    public static Encoder leftEnc;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	
    // Motor init
    	// Right
        rightMotor1 = new WPI_TalonSRX(1);
        rightMotor2 = new WPI_TalonSRX(2);
        rightMotor3E = new WPI_TalonSRX(3);
        //Left
        leftMotor1E = new WPI_TalonSRX(4);
        leftMotor2 = new WPI_TalonSRX(5);
        leftMotor3 = new WPI_TalonSRX(6);
        
    // Encoder init
        // Right
        rightEnc = new Encoder(2, 3, false, EncodingType.k4X);
        rightEnc.setDistancePerPulse(1.0);
        rightEnc.setPIDSourceType(PIDSourceType.kRate);
        LiveWindow.addSensor("DriveTrain", "rightEnc", rightEnc);
        // Left
        leftEnc = new Encoder(0, 1, false, EncodingType.k4X);
        leftEnc.setDistancePerPulse(1.0);
        leftEnc.setPIDSourceType(PIDSourceType.kRate);
        LiveWindow.addSensor("DriveTrain", "leftEnc", leftEnc);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
