 // RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot18.subsystems;

import org.usfirst.frc1073.robot18.RobotMap;
import org.usfirst.frc1073.robot18.commands.*;

import com.ctre.CANTalon;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Drivetrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
<<<<<<< HEAD:src/org/usfirst/frc1073/robot18/subsystems/Drivetrain.java
    private final WPI_TalonSRX rightMotor1 = RobotMap.rightMotor1;
    private final WPI_TalonSRX rightMotor2 = RobotMap.rightMotor2;
    private final WPI_TalonSRX rightMotor3E = RobotMap.rightMotor3E;
    private final WPI_TalonSRX leftMotor1E = RobotMap.leftMotor1E;
    private final WPI_TalonSRX leftMotor2 = RobotMap.leftMotor2;
    private final WPI_TalonSRX leftMotor3 = RobotMap.leftMotor3;
    private final Encoder rightEnc = RobotMap.rightEnc;
    private final Encoder leftEnc = RobotMap.leftEnc;
=======
    private final WPI_TalonSRX rightMotor1 = RobotMap.driveTraindriveTrainRightMotor1;
    private final WPI_TalonSRX rightMotor2 = RobotMap.driveTraindriveTrainRightMotor2;
    private final WPI_TalonSRX rightMotor3E = RobotMap.driveTraindriveTrainRightMotor3E;
    private final WPI_TalonSRX leftMotor1 = RobotMap.driveTraindriveTrainLeftMotor1;
    private final WPI_TalonSRX leftMotor2 = RobotMap.driveTraindriveTrainLeftMotor2;
    private final WPI_TalonSRX leftMotor3E = RobotMap.driveTraindriveTrainLeftMotor3E;
    private final Encoder rightEnc = RobotMap.driveTraindriveTrainRightEnc;
    private final Encoder leftEnc = RobotMap.driveTraindriveTrainLeftEnc;
>>>>>>> c6e618dcf92f2be930c2f981793c959441e3f1e7:src/org/usfirst/frc1073/robot18/subsystems/DriveTrain.java

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private boolean leftInverted = true;
    private boolean rightInverted = true;
    
<<<<<<< HEAD:src/org/usfirst/frc1073/robot18/subsystems/Drivetrain.java
	public Drivetrain() {
	    	leftMotor1E.setInverted(leftInverted);
=======
	public DriveTrain() {
	    	leftMotor1.setInverted(leftInverted);
>>>>>>> c6e618dcf92f2be930c2f981793c959441e3f1e7:src/org/usfirst/frc1073/robot18/subsystems/DriveTrain.java
	    	leftMotor2.setInverted(leftInverted);
	    	leftMotor3E.setInverted(leftInverted);
	    	rightMotor1.setInverted(rightInverted);
	    	rightMotor2.setInverted(rightInverted);
	    	rightMotor3E.setInverted(rightInverted);
	    	
	    	leftMotor2.follow(leftMotor3E);
	    	leftMotor1.follow(leftMotor3E);
	    	rightMotor2.follow(rightMotor3E);
	    	rightMotor1.follow(rightMotor3E);
	}
    
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    	setDefaultCommand(new Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    //Used for non-PID auto routines (semi-temp).
    public void basicDrive(double left, double right) {
    	
    	rightMotor3E.set(right);
    	leftMotor3E.set(left);
    }

}

